service: jwt

package:
  individually: true  # Create an optimized package for our functions

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs16.x
  stackTags:
    stack: ${self:service}
  tags:
    stack: ${self:service}
  stage: dev
  region: us-east-1
  logRetentionInDays: 30

custom:
  stage: ${opt:stage, self:provider.stage}
  authorizer:
    arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:custom.stage}-authorizer
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
    identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
    type: token

functions:

  get-token:
    handler: functions/get-token.get
    events:
      - http:
          path: get-token
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action: ssm:GetParameters
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:service}/${self:custom.stage}/*

  read-account:
    handler: functions/read-account.read
    events:
      - http:
          path: read-account
          method: get
          authorizer: ${self:custom.authorizer}
          cors: true
    environment:
      TABLE: !Ref Table
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:Query
        Resource: !GetAtt Table.Arn

  authorizer:
    handler: functions/authorizer.authorizer
    iamRoleStatements:
      - Effect: Allow
        Action: ssm:GetParameters
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:service}/${self:custom.stage}/*

  create-account:
    handler: functions/create-account.create
    events:
      - http:
          path: create-account
          method: post
    environment:
      TABLE: !Ref Table
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt Table.Arn

  update-account:
    handler: functions/update-account.update
    events:
      - http:
          path: update-account
          method: post
          authorizer: ${self:custom.authorizer}
          cors: true
    environment:
      TABLE: !Ref Table
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource: !GetAtt Table.Arn

resources:
  Resources:

    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: account
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: account
            AttributeType: S

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

  Outputs:

    ApiUrl:
      Value:
        !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.${opt:region, self:provider.region}.amazonaws.com/${self:custom.stage}'
