service: jwt

package:
  individually: true  # Create an optimized package for our functions

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  logRetentionInDays: 30

custom:
  stage: ${opt:stage, self:provider.stage}
  authorizer:
    arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:custom.stage}-authorizer
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
    identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
    type: token

functions:

  get-token:
    handler: functions/get-token.get
    events:
      - http:
          path: get-token
          method: post

  read-account:
    handler: functions/read-account.read
    events:
      - http:
          path: read-account
          method: get
          authorizer: ${self:custom.authorizer}

  authorizer:
    handler: functions/authorizer.authorizer

resources:
  Resources:

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
