service: jwt

package:
  individually: true  # Create an optimized package for our functions

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  logRetentionInDays: 30

functions:

  get-token:
    handler: functions/get-token.get
    events:
      - http:
          path: get-token
          method: post
